### ISSUE TITLE
Currences

### ISSUE THREAD

**Issue by kabetov** [coinbase/coinbase-commerce-opencart#1]
On the store I set up the currency - EUR.
But in the Cart the price was in RUB. For example 1000 RUB (which means 14 EUR).
Totally at the https://commerce.coinbase.com/charges/ the price was 14 RUB.

**Comment by guacamoli** [comment]
Hi @kabetov, are you still seeing this issue? Can you provide some more details?

**Comment by kabetov** [comment]
Hello @guacamoli Yes, please https://docs.google.com/document/d/1rcYSv3QROikCbDjRMMuhyR-N0_eovUunognKx_-H1gI/edit?usp=sharing

**Comment by guacamoli** [comment]
@kabetov, thanks again for reporting the issue and providing details! We've pushed a fix for the issue and will be updating the plugin soon. Thanks!

**Comment by kabetov** [comment]
@guacamoli please inform when I can test it)

**Comment by justinpobrien** [comment]
Hello @kabetov we just published a new release with the fix: https://github.com/coinbase/coinbase-commerce-opencart/releases/tag/v1.0.1
