### ISSUE TITLE
Getting The installation error

### ISSUE THREAD

**Issue by RockHood007** [coinbase/coinbase-commerce-opencart#6]
Hi,

I have installed the extension on my website opencart Version 2.3.0.2
When I try to enable the extension I receive the below error

Notice: Undefined index: user_token in /home/kavita25/public_html/admin/controller/extension/payment/coinbase.php on line 25Notice: Undefined index: user_token in /home/kavita25/public_html/admin/controller/extension/payment/coinbase.php on line 26Notice: Undefined index: user_token in /home/kavita25/public_html/admin/controller/extension/payment/coinbase.php on line 52Notice: Undefined index: user_token in /home/kavita25/public_html/admin/controller/extension/payment/coinbase.php on line 56Notice: Undefined index: user_token in /home/kavita25/public_html/admin/controller/extension/payment/coinbase.php on line 60Notice: Error: Could not load template /home/kavita25/public_html/admin/view/template/extension/payment/coinbase.tpl! in /home/kavita25/public_html/vqmod/vqcache/vq2-system_storage_modification_system_library_template_php.php on line 23

Please help

**Comment by guacamoli** [comment]
Hey @RockHood007, we created a branch that supports your version of opencart -- https://github.com/coinbase/coinbase-commerce-opencart/tree/2.3.0.x
